#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  Corpse  -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
corpse-limit: 3 # each player can only have 3 corpses at a time
corpse-grace-period: 10 # in minutes, the amount of time the corpse is accessible to only the dead player
corpse-decay-time: 2880 # in minutes

soulbound-cost: 100 # cost to soulbind an item

# supports player placeholders for the clicker (playerName) etc.., (corpseName) for the name of the dead player
# you can also use (graceTimeLeft|HH:mm:ss) to display what time is left of the grace period
# you can replace HH:mm:ss with a different time format
corpse-grace-message: "(corpseName)'s corpse is currently locked! It will be unlocked in (graceTimeLeft|HH:mm:ss)"
corpse-pickupsouls-message: "<green>Found (corpseSouls) souls on (corpseName)'s corpse."
corpse-nosouls-message: "<red>No souls were found on this corpse."
corpse-name: "<red>(corpseName)'s corpse" # name in gui
corpse-drop-items-on-spawn-fail: true

#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  Damage  -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
damage-debuff-duration: 5 # in minutes
damage-debuff-percentage: 10
damage-debuff-max-stack: 5 # max amount of times the player can stack their damage debuff
damage-debuff-message: '<red>You have blood on your hands' # Message sent when a player kills another player

#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  Items  -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
round-up: true # true to round up, false to round down

items:
  GOLD_INGOT:
    min: 50 # Percentage is in whole numbers, so 50 is 50% of items taken. In this case if you have 10 golden ingots, it'll take from 5 to 10 of them from you.
    max: 100
  IRON_ORE:
    min: 50
    max: 100
