name: RespawnHandler
main: me.cookie.RespawnHandler
version: 1.1.0
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib:1.6.0'
api-version: 1.18
depend:
  - Citizens
  - CookieCore

commands:
  souls:
    permission: 'respawnhandler.souls'
    usage: '/souls'
    description: 'Admin command to set the amount of souls a player has.'
    aliases:
      - soul
      - souls
  soulbound:
    permission: 'respawnhandler.soulbound'
    usage: '/soulbound'
    description: 'Opens a soulbound GUI where a player can soulbind their items.'
    aliases:
      - soulbound
      - soulbind
      - soulbounditems
      - soulbinditems
      - soulbounditem
      - soulbinditem