name: RespawnHandler
main: me.cookie.RespawnHandler
version: 1.2.2
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib:1.7.0'
api-version: 1.18
depend:
  - Citizens
  - CookieCore

commands:
  soulsadmin:
    permission: 'respawnhandler.soulsadmin'
    usage: '/soulsadmin'
    description: 'Admin command to set the amount of souls a player has.'
    aliases:
      - souladmin
  soulbound:
    permission: 'respawnhandler.soulbound'
    usage: '/soulbound'
    description: 'Opens a soulbound GUI where a player can soulbind their items.'
    aliases:
      - soulbind
  corpses:
    permission: 'respawnhandler.corpses'
    usage: '/corpses'
    description: 'Admin command to manage corpses.'
    aliases:
      - corpse
